name: Build-Debug

on:
  push:
    branches:
      - "master"
    tags:
      - "!*" # not a tag push
  pull_request:
    branches:
      - "master"

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
      - run: dotnet build src/WebSerializer -c Debug
      - run: dotnet test tests/WebSerializer.Tests -c Debug < /dev/null